### ISSUE TITLE
would you consider developing a separate chatgpt version or adding chatgpt support

### ISSUE THREAD

**Issue by ikexue** [bclswl0827/ChatGemini#21] opened 2024-02-13 15:36 UTC
This is the best Gemini web app I've ever seen, It's amazing，would you consider developing a separate chatgpt version or adding interface support?

**Comment by bclswl0827** [comment] 2024-02-13 18:28
Duplicate of https://github.com/bclswl0827/ChatGemini/issues/4
But leaving its interfaces is always a good design, I will try to improve it, so that you can fork and support other models by yourself with ease.

**Comment by ikexue** [comment] 2024-02-14 08:31
Thanks

**Closed** 2024-02-14 08:32 UTC
Labels: duplicate
